server:
  servlet:
    context-path: /
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zyt123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0

#mybatis-plus:
#  config-location: classpath*:/mapper/**/*.xml